### ISSUE TITLE
测试没问题，但是研究了半天。数据没办法搞定

### ISSUE THREAD

**Issue by hardy110** [gsyyysg/StockFormer#10]
测试没问题，但是研究了半天。也看不到csv的处理代码，不知道csi300的数据csv怎么产生的，只看出来price是收盘价，有谁知道csv的open，close等值怎么根据price处理的？

**Comment by hardy110** [comment]
感觉做了最大最小化处理？

**Comment by hardy110** [comment]
已解决

**Comment by chenchaoyu** [comment]
请问是怎么解决的，知道open，high，low，close这几个数据是怎么处理得到的吗

**Comment by xbkaishui** [comment]
hi 怎么处理的？ 能否解释下

**Comment by Dreamlikec** [comment]
price 列它也不是收盘价啊~ 这个文件是怎么处理的有人知道吗？
