### ISSUE TITLE
When the program was running to load zipfile, an error occurred. It is werid.

### ISSUE THREAD

**Issue by zhrli** [gsyyysg/StockFormer#9]
RuntimeError: Error(s) in loading state_dict for SACPolicy:
	size mismatch for actor.mu.weight: copying a param with shape torch.Size([88, 256]) from checkpoint, the shape in current model is torch.Size([31064, 256]).
	size mismatch for actor.mu.bias: copying a param with shape torch.Size([88]) from checkpoint, the shape in current model is torch.Size([31064]).
	size mismatch for actor.log_std.weight: copying a param with shape torch.Size([88, 256]) from checkpoint, the shape in current model is torch.Size([31064, 256]).
	size mismatch for actor.log_std.bias: copying a param with shape torch.Size([88]) from checkpoint, the shape in current model is torch.Size([31064]).
	size mismatch for critic.qf0.0.weight: copying a param with shape torch.Size([256, 11440]) from checkpoint, the shape in current model is torch.Size([256, 42416]).
	size mismatch for critic.qf1.0.weight: copying a param with shape torch.Size([256, 11440]) from checkpoint, the shape in current model is torch.Size([256, 42416]).
	size mismatch for critic_target.qf0.0.weight: copying a param with shape torch.Size([256, 11440]) from checkpoint, the shape in current model is torch.Size([256, 42416]).
	size mismatch for critic_target.qf1.0.weight: copying a param with shape torch.Size([256, 11440]) from checkpoint, the shape in current model is torch.Size([256, 42416]).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/sda/DL/AI4F/StockFormer/code/train_rl.py", line 226, in <module>
    results = DRLAgent.DRL_prediction_load_from_file(model_name='maesac',environment=test_trade_gym, cwd=model_path)
  File "/mnt/sda/DL/AI4F/StockFormer/code/MySAC/models/DRLAgent.py", line 188, in DRL_prediction_load_from_file
    raise ValueError("Fail to load agent!")
ValueError: Fail to load agent!

**Comment by yo-yoo** [comment]
Hi, I met the same error, have you solved it?
Many thanks if you can share it.
